name: Plant Plasticity
baseurl: /
imagesurl: /images/
postersurl: /resources/posters/
publicationsurl: /resources/publications/
resourcesurl: /resources/
cssurl: /source/css/
permalink: pretty
markdown: kramdown
version: 0.3.3
